use_frameworks!

platform :ios, '8.0'

target 'commonTools_Example' do
  pod 'commonTools', :path => '../'

  target 'commonTools_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
